const names = {
  en: ["Business analysis", "Smart Map", "Opportunity Score", "Competition analytics", "Demographics", "Market gaps", "AI Advisor", "Location comparison", "Opportunity Scanner", "Pricing intelligence", "Dynamic Market", "Planned businesses", "Future market pressure", "Digital Twin", "Business Health", "Reports", "Export", "Financial forecasts", "Multiple projects", "Team tools", "Commercial properties", "Market alerts", "API access", "Custom integrations", "Network expansion", "Enterprise intelligence", "Administration"],
  ru: ["Бизнес-анализ", "Умная карта", "Оценка возможностей", "Анализ конкурентов", "Демография", "Ниши рынка", "ИИ-консультант", "Сравнение локаций", "Поиск возможностей", "Анализ цен", "Динамика рынка", "Планы открытия", "Будущая конкуренция", "Цифровой двойник", "Состояние бизнеса", "Отчёты", "Экспорт", "Финансовые прогнозы", "Несколько проектов", "Командная работа", "Коммерческая недвижимость", "Уведомления рынка", "Доступ к API", "Интеграции", "Расширение сети", "Корпоративная аналитика", "Управление доступом"],
  kk: ["Бизнес талдау", "Ақылды карта", "Мүмкіндік бағасы", "Бәсекелестерді талдау", "Демография", "Нарықтағы бос нишалар", "ЖИ кеңесші", "Орындарды салыстыру", "Мүмкіндіктерді іздеу", "Бағаларды талдау", "Нарық динамикасы", "Бизнес ашу жоспарлары", "Болашақ бәсеке", "Цифрлық егіз", "Бизнес жағдайы", "Есептер", "Экспорт", "Қаржылық болжамдар", "Бірнеше жоба", "Командалық жұмыс", "Коммерциялық жылжымайтын мүлік", "Нарық хабарламалары", "API қолжетімділігі", "Интеграциялар", "Желіні кеңейту", "Корпоративтік талдау", "Қолжетімділікті басқару"]
};
names.en.push("Best Area Finder");
names.ru.push("Лучший район");
names.kk.push("Үздік аудан");
const keys = ["BASIC_ANALYSIS", "SMART_MAP", "OPPORTUNITY_SCORE", "ADVANCED_COMPETITION", "DEMOGRAPHICS", "MARKET_GAP", "AI_ADVISOR", "LOCATION_COMPARISON", "OPPORTUNITY_SCANNER", "PRICING", "DYNAMIC_MARKET", "PLANNED_BUSINESS", "FUTURE_MARKET_PRESSURE", "DIGITAL_TWIN", "BUSINESS_HEALTH", "REPORTS", "EXPORT", "FORECASTING", "MULTIPLE_PROJECTS", "TEAM_TOOLS", "COMMERCIAL_PROPERTIES", "PREMIUM_ALERTS", "API_ACCESS", "CUSTOM_INTEGRATIONS", "EXPANSION", "ENTERPRISE_TOOLS", "ADMIN_TOOLS", "BEST_DISTRICT_FINDER"];
const text = {
  en: { upgrade: "Plans and access", unlock: "Unlock", available: "Available on", current: "Current plan", request: "Request access", sent: "Request sent. Your current access has not changed.", signIn: "Sign in", restricted: "Administrator access required", adminOnly: "This area is reserved for account administrators.", loading: "Checking account access...", error: "Account access could not be verified. Please try again.", retry: "Try again", included: "Included", free: "Free", contact: "Contact to activate", pending: "Sending...", title: "Choose the access your business needs", intro: "Start with analysis and a map. Add deeper intelligence as your work grows.", billing: "Online payment is not connected yet. Requests are reviewed by an administrator; sending a request does not activate a subscription.", allPrevious: "Everything in", admin: "Administrator: full access", noResults: "Advanced analysis is available after upgrading.", account: "Account", users: "Users", save: "Save changes", saved: "Access updated", next: "Next", previous: "Previous", expiry: "Expires at (UTC)", noExpiry: "No expiration", competitors: "Observed competitors", city: "City", category: "Category", budget: "Budget", basic: "Basic market analysis", distribution: "Competitors by area", empty: "No observed businesses were returned for this query.", open: "Open feature", newLogin: "Sign in to request a plan.", future: "Planned capabilities", futureNote: "Digital Twin, Business Health, dedicated team tools and developer API integrations are not yet available. They are not included as delivered features." },
  ru: { upgrade: "Тарифы и доступ", unlock: "Открыть доступ:", available: "Доступно на", current: "Текущий тариф", request: "Запросить подключение", sent: "Запрос отправлен. Текущий доступ не изменён.", signIn: "Войти", restricted: "Нужны права администратора", adminOnly: "Этот раздел доступен администраторам аккаунтов.", loading: "Проверяем доступ...", error: "Не удалось проверить доступ. Попробуйте ещё раз.", retry: "Повторить", included: "Включено", free: "Бесплатно", contact: "Подключение по запросу", pending: "Отправляем...", title: "Выберите доступ для задач вашего бизнеса", intro: "Начните с анализа и карты. Подключайте расширенную аналитику по мере роста задач.", billing: "Онлайн-оплата пока не подключена. Администратор рассматривает запрос; отправка запроса не активирует подписку.", allPrevious: "Всё из", admin: "Администратор: полный доступ", noResults: "Расширенный анализ доступен после подключения тарифа.", account: "Аккаунт", users: "Пользователи", save: "Сохранить", saved: "Доступ обновлён", next: "Далее", previous: "Назад", expiry: "Срок действия (UTC)", noExpiry: "Без срока", competitors: "Найденные конкуренты", city: "Город", category: "Категория", budget: "Бюджет", basic: "Базовый анализ рынка", distribution: "Конкуренты по районам", empty: "По этому запросу источники не вернули организации.", open: "Открыть раздел", newLogin: "Войдите, чтобы запросить подключение.", future: "В разработке", futureNote: "Цифровой двойник, состояние бизнеса, отдельные командные инструменты и интеграции API пока недоступны. Они не входят в список готовых функций." },
  kk: { upgrade: "Тарифтер мен қолжетімділік", unlock: "Қолжетімділікті ашу:", available: "Қолжетімді тариф:", current: "Ағымдағы тариф", request: "Қосылуға өтінім беру", sent: "Өтінім жіберілді. Ағымдағы қолжетімділік өзгерген жоқ.", signIn: "Кіру", restricted: "Әкімші құқығы қажет", adminOnly: "Бұл бөлім аккаунт әкімшілеріне арналған.", loading: "Қолжетімділік тексерілуде...", error: "Қолжетімділікті тексеру мүмкін болмады. Қайталап көріңіз.", retry: "Қайталау", included: "Тарифке кіреді", free: "Тегін", contact: "Өтінім бойынша қосылу", pending: "Жіберілуде...", title: "Бизнес міндеттеріңізге сай тарифті таңдаңыз", intro: "Талдау мен картадан бастаңыз. Міндеттер көбейген сайын кеңейтілген талдауды қосыңыз.", billing: "Онлайн төлем әзірге қосылмаған. Өтінімді әкімші қарайды; өтінім жіберу жазылымды белсендірмейді.", allPrevious: "Барлық мүмкіндіктер:", admin: "Әкімші: толық қолжетімділік", noResults: "Кеңейтілген талдау тарифті қосқаннан кейін қолжетімді.", account: "Аккаунт", users: "Пайдаланушылар", save: "Сақтау", saved: "Қолжетімділік жаңартылды", next: "Келесі", previous: "Алдыңғы", expiry: "Аяқталу мерзімі (UTC)", noExpiry: "Мерзімсіз", competitors: "Табылған бәсекелестер", city: "Қала", category: "Санат", budget: "Бюджет", basic: "Нарықтың негізгі талдауы", distribution: "Аудандар бойынша бәсекелестер", empty: "Бұл сұрау бойынша дереккөздер ұйымдарды қайтармады.", open: "Бөлімді ашу", newLogin: "Өтінім беру үшін кіріңіз.", future: "Әзірленіп жатқан мүмкіндіктер", futureNote: "Цифрлық егіз, бизнес жағдайы, жеке командалық құралдар және API интеграциялары әзірге қолжетімсіз. Олар дайын мүмкіндіктер тізіміне кірмейді." }
};
export function accessCopy(language = "kk") {
  const locale = text[language] ? language : "kk";
  return { ...text[locale], features: Object.fromEntries(keys.map((key, i) => [key, names[locale][i]])) };
}
